apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: memesgen-certificate
  namespace: development
spec:
  dnsNames:
    - dev.juliusoh.tech
  secretName: memesgen-certificate
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer