name: memesgen-react-client

on:
  push:
    branches:
      - master
      - main

env:
  GCP_PROJECT: memesgen
  CI_PROJECT_NAME: memesgen
  GCP_LOCATION: us-west1
  GCP_CLUSTER: memesgen
  GCP_CI_SERVICE_KEY: ${{ secrets.GCP_CI_SERVICE_KEY }}

jobs:
  build-and-deploy:
    name: bundle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: bundle
      working-directory: ./frontend
      run: |
        unset CI
        npm i
        npm run build

    - name: authenticate gcp
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_CI_SERVICE_KEY }}

    - name: build
      working-directory: ./frontend
      run: |
        gcloud auth configure-docker
        docker build -t $CI_PROJECT_NAME .
        docker tag $CI_PROJECT_NAME "us.gcr.io/$GCP_PROJECT/$CI_PROJECT_NAME"
        docker tag $CI_PROJECT_NAME "us.gcr.io/$GCP_PROJECT/$CI_PROJECT_NAME:$GITHUB_SHA"
        docker push "us.gcr.io/$GCP_PROJECT/$CI_PROJECT_NAME" --all-tags

    - name: authenticate
      run: |
        export KUBECONFIG=kube.conf && gcloud container clusters get-credentials $GCP_CLUSTER --zone $GCP_LOCATION --project $GCP_PROJECT
        kubectl get pods

    - name: deploy
      working-directory: ./frontend
      run: |
        export KUBECONFIG=kube.conf
        helm upgrade --install $CI_PROJECT_NAME .infra \
        --namespace development \
        --create-namespace \
        --set image.tag=$GITHUB_SHA